name: chatify
description: "A modern social media application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  iconsax_flutter: ^1.0.0
  nb_utils: ^7.0.4
  emoji_picker_flutter: ^3.0.0
  webview_flutter: ^3.0.4
  loading_animation_widget: ^1.2.1
  cached_network_image: ^3.4.1
  camera: ^0.11.0+2
  vibration: ^2.0.0
  cupertino_icons: ^1.0.6
  audioplayers: ^5.2.1
  flutter_reaction_button: ^3.0.0+3
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  table_calendar: ^3.1.2
  flutter_mentions: ^2.0.1
  url_launcher: ^6.3.0
  flutter_staggered_grid_view: ^0.7.0

  # State Management
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  # Network
  http: ^1.2.0
  dio: ^5.4.1
  connectivity_plus: ^5.0.2

  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2

  # Utils
  intl: ^0.19.0
  logger: ^2.0.2+1
  uuid: ^4.3.3

  # Animations
  lottie: ^3.1.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
